---
- name: Ubuntu Restart Checker
  hosts: all
  become: yes
  tasks:
    - name: Detecting systems that need reboot
      debug:
        msg: "Checking system {{ lookup('ansible.builtin.file', '/var/run/reboot-required') }}"
       
    - name: Reboot if required
        reboot:
          when: lookup == *** System restart required ***