---
- name: Ubuntu Restart Checker
  hosts: all
  become: yes
  tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
          register: reboot_required_file
       
    - name: Reboot if required
        reboot:
          when: reboot_required_file == *** System restart required ***