---
- name: Ubuntu Restart Checker
  hosts: all
  become: yes
  tasks:
    - name: Detecting systems that need reboot
      ansible.builtin.debug:
      with_file: "/var/run/reboot-required"
      register: rebootCheck
    
    - name: Rebooting system(s)  
      reboot:
      when: rebootCheck == '*** System restart required ***'