---
- name: Ubuntu Restart Checker
  hosts: all
  become: yes
  tasks:
    - name: Detecting systems that need reboot
      stat: 
        path: "/var/run/reboot-required"
      register: rebootCheck
    
    - name: Rebooting system(s)  
      reboot:
      when: rebootCheck.stat.exist