---

- name: Tailscale Updater
  hosts: all
  ignore_unreachable: true
  ignore_errors: true
  tasks:
    - name: Updating Tailscale
      ansible.windows.win_shell: Tailscale update -yes
      
      